## Import libraries

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.display.max_rows = None

## Import dataset and preview

In [3]:
df = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding ='latin-1')
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [59]:
## check the distribution of the dataset

df.describe().T

,count,mean,std,min,25%,50%,75%,max
Area Code,60943.0,134.265576,72.605709,4.0,74.0,136.00,195.00,276.0
Item Code,60943.0,2687.176706,146.055739,2501.0,2562.0,2630.00,2775.00,2961.0
Element Code,60943.0,3814.856456,2212.007033,511.0,684.0,5142.00,5511.00,5911.0
Y2014,59354.0,134.196282,1567.663696,-1796.0,0.0,0.09,8.34,176405.0
Y2015,59395.0,135.235966,1603.403984,-3161.0,0.0,0.08,8.46,181137.0
Y2016,59408.0,136.555222,1640.007194,-3225.0,0.0,0.08,8.43,185960.0
Y2017,59437.0,140.917765,1671.862359,-1582.0,0.0,0.10,9.00,190873.0
Y2018,59507.0,143.758381,1710.782658,-3396.0,0.0,0.07,9.00,195875.0

## Questions and Answers

### What is the total sum of Wine produced in 2015 and 2018 respectively?

In [60]:
df.groupby('Item').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
"Aquatic Animals, Others",47420,966381,1139179,14.55,9.26,6.17,5.92,5.92
Aquatic Plants,51178,1057275,1278386,507.29,631.23,470.21,452.02,452.02
"Aquatic Products, Other",52570,1160712,1320249,519.62,638.42,475.08,456.65,456.65
Bananas,68496,1338880,1894890,53267.31,55046.76,54376.07,53008.82,55549.23
Barley and products,76321,1432410,2243002,25384.66,29153.44,24706.08,26176.98,31253.70
Beans,78001,1476680,2263509,19207.68,20315.77,19037.50,21351.42,20121.14
Beer,65975,1314720,1813728,41879.92,42053.67,42540.48,41962.92,41612.12
"Beverages, Alcoholic",65918,1313052,1807946,3067.16,2818.38,2834.92,3115.24,2979.21
"Beverages, Fermented",65203,1299273,1774758,50536.78,47447.92,45478.53,43958.75,46874.94
Bovine Meat,70033,1431044,1963251,22098.60,22766.42,22411.18,22612.86,23926.30
"Butter, Ghee",60516,1238480,1594919,1249.29,1165.69,1199.87,1116.68,1175.59
Cassava and products,73208,1385004,2081916,405442.57,410235.89,415730.20,401440.17,435862.14
Cephalopods,58593,1233636,1571763,423.03,496.95,503.64,532.14,532.07
Cereals - Excluding Beer,95370,2074170,2976719,851924.06,845669.36,875974.56,905221.25,903280.79
"Cereals, Other",79505,1489320,2326237,18689.11,18912.55,19877.56,20615.95,22125.96
"Citrus, Other",70239,1367122,1954812,14533.46,15188.91,15515.30,15650.97,15804.14
Cloves,53398,1064726,1420590,77.37,77.29,78.27,82.32,82.36
Cocoa Beans and products,70862,1398123,1998287,7166.65,7671.59,7510.86,8638.32,8353.83
Coconut Oil,69418,1330248,1959863,517.56,556.18,549.43,516.99,537.70
Coconuts - Incl Copra,74263,1410560,2104761,6568.33,6646.28,6577.23,6478.91,6526.12
Coffee and products,72724,1433350,2070618,3677.92,3849.99,4115.34,3861.45,4009.65
Cottonseed,44285,841911,1768564,8108.00,7998.00,8093.00,8623.00,8802.00
Cottonseed Oil,67319,1287500,1881106,1379.76,1507.90,1366.75,1403.25,1421.56
Cream,55778,1141088,1421946,237.52,233.37,267.84,228.95,271.61
Crustaceans,64831,1338260,1761859,734.07,732.86,717.30,834.82,833.61
Dates,64881,1278072,1771007,10183.80,11108.74,10904.81,11088.61,11454.52
Demersal Fish,62436,1292616,1677632,5845.93,6123.88,5691.28,6618.70,6616.23
Eggs,154150,3250703,4426246,20563.36,21431.48,20428.82,21749.74,20638.48
"Fats, Animals, Raw",79842,1636726,2341974,1596.09,1729.80,1614.01,1783.67,1707.11
"Fish, Body Oil",56619,1154115,1462871,170.51,193.73,167.09,219.65,219.65
"Fish, Liver Oil",48755,979264,1197204,38.13,6.36,15.87,48.02,48.02
"Fish, Seafood",71756,1583600,2039247,43240.02,43293.41,43727.14,44849.35,44810.20
Freshwater Fish,64920,1333563,1761607,13161.92,13195.86,13908.83,14258.00,14244.98
Fruits - Excluding Wine,79433,1725129,2313131,273559.54,282857.19,277458.49,284309.07,290381.46
"Fruits, Other",76833,1506750,2224160,53970.46,57504.33,57730.21,59463.60,61370.30
Grand Total,18060,391635,90990,119183.84,118937.92,118434.34,119264.82,119388.06
Grapefruit and products,69139,1340469,1896997,2359.01,2352.21,2129.03,2137.02,2449.18
Grapes and products (excl wine),70255,1367640,1946827,13820.84,14607.88,14235.15,14591.98,13992.75
Groundnut Oil,70147,1355444,1971148,5479.80,5561.17,5511.52,5389.20,5463.60
Groundnuts (Shelled Eq),82299,1577052,2457038,42384.73,42199.35,43962.23,44684.53,46513.58
Honey,69241,1413675,1908893,679.11,713.12,664.78,660.07,681.56
Infant food,59745,1197960,1547996,328.49,340.38,331.92,311.92,298.01
"Lemons, Limes and products",70391,1358240,1938946,3429.42,3667.51,3600.68,4191.49,4220.50
Maize Germ Oil,64256,1234196,1747258,874.59,950.64,1000.13,1075.37,865.77
Maize and products,91790,1727118,2832303,291731.71,287659.14,294568.76,323471.75,297383.10
"Marine Fish, Other",64234,1323956,1733842,3253.42,3153.59,3250.75,3136.63,3134.78
Meat,72011,1583334,2037234,65331.31,66042.60,66050.65,67833.55,70553.53
"Meat, Other",69390,1416730,1930240,5182.20,5287.66,5293.44,5324.82,5412.90
Milk - Excluding Butter,168482,3657276,5058264,268099.98,266446.14,272380.98,276703.90,281018.64
Millet and products,77725,1401969,2288150,40339.67,40459.94,43469.33,41836.61,49783.34
Miscellaneous,121457,2654213,3195541,6582.96,6803.24,6469.24,6921.83,6715.51
"Molluscs, Other",59450,1228548,1543765,147.51,134.91,156.34,157.34,157.20
Mutton & Goat Meat,65536,1338680,1780997,9661.64,9625.44,9731.22,9769.78,9769.46
Nuts and products,70304,1336724,1962812,6523.47,6939.31,6319.69,6875.08,6886.56
Oats,69915,1315868,1957915,726.54,930.02,844.96,902.97,1029.29
Offals,70523,1549070,1973858,7659.28,7841.07,7843.57,8252.88,8751.58
"Offals, Edible",70523,1439136,1973858,7659.28,7841.07,7843.57,8252.88,8751.58
Oilcrops,94222,2056578,2933349,158075.67,163097.03,161193.66,166985.23,180845.03
"Oilcrops Oil, Other",74081,1432644,2118276,5600.20,5398.90,5181.81,5925.84,5580.14
"Oilcrops, Other",79141,1506020,2406571,6410.95,6584.80,6689.05,6269.10,6464.42
Olive Oil,68333,1315800,1883123,1467.44,1711.65,1499.27,1484.14,1983.76
Olives (including preserved),64335,1225114,1727253,9002.41,12547.69,11028.51,9930.20,12824.75
Onions,67525,1298398,1848334,33467.52,36973.65,37435.12,39656.98,40608.41
"Oranges, Mandarines",73421,1425606,2075758,33363.64,33421.50,31442.59,34602.81,34471.68
Palm Oil,71538,1391580,2077827,26807.94,27229.24,25725.04,32462.95,32732.58
Palm kernels,35467,686616,1372593,50648.00,52524.00,53669.00,56218.00,58841.00
Palmkernel Oil,66182,1275120,1915385,1570.26,1408.94,1381.47,1517.36,1516.58
Peas,72290,1349910,2012632,2432.99,2472.35,2309.69,2425.43,2353.80
Pelagic Fish,70739,1472679,2031808,19998.64,19838.14,19957.99,19801.15,19779.84
Pepper,64603,1269840,1731589,137.74,137.04,147.84,142.76,141.51
Pigmeat,68591,1410228,1918369,5890.26,5914.61,5933.10,6099.27,6188.40
Pimento,65712,1288808,1785669,2481.19,2754.14,2894.98,2812.22,2847.67
Pineapples and products,70539,1377068,1968060,14363.66,14276.56,14568.95,15694.20,16120.73
Plantains,54725,1051632,1479569,64682.48,65037.18,63021.24,63619.19,65213.66
Population,12040,225090,261540,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Potatoes and products,86083,1622371,2582884,75754.48,78655.23,74097.50,74990.58,77793.56
Poultry Meat,69333,1418946,1937247,22472.52,22440.36,22681.72,23985.90,25257.39
Pulses,86362,1889239,2638522,56711.40,59361.19,61508.09,65535.31,64771.23
"Pulses, Other and products",83586,1595674,2515138,35061.63,36569.14,40138.81,41741.43,42264.26
Rape and Mustard Oil,65777,1271556,1849681,228.88,312.38,276.41,329.98,247.25
Rape and Mustardseed,71380,1355740,1995188,667.00,663.00,621.00,628.00,666.00
Rice and products,89260,1879350,2744539,155122.23,150657.00,161150.98,166354.09,167195.55
Ricebran Oil,33527,598792,1010165,0.00,0.00,0.00,0.00,0.00
"Roots, Other",72036,1378496,2091445,42001.37,42757.91,42883.23,43389.37,43797.46
Rye and products,63769,1192110,1788655,284.24,428.14,303.19,306.41,324.35
Sesame seed,71143,1365013,2121769,8044.24,6769.62,7819.98,7955.60,8492.35
Sesameseed Oil,65744,1230183,1814000,609.73,587.58,716.58,663.10,589.79
Sorghum and products,84070,1525908,2456864,86939.64,82725.53,91609.56,85468.93,91504.28
Soyabean Oil,70775,1362630,1986336,9033.32,10381.77,10151.87,10683.31,11422.03
Soyabeans,76891,1456350,2225300,15067.19,16412.47,15920.30,18574.99,24180.95
Spices,70582,1522883,1945922,4421.98,5059.08,6839.95,6801.63,6406.66
"Spices, Other",66306,1296050,1783586,1695.48,2068.57,3692.79,3744.19,3318.96
Starchy Roots,90330,1959318,2763138,792393.91,802578.22,823223.18,825497.34,855955.18
Stimulants,75449,1656774,2186289,13587.83,14180.97,14314.71,15119.56,15214.78
Sugar & Sweeteners,82006,1783217,2435532,78235.83,80214.74,80920.20,86952.63,87663.08
Sugar (Raw Equivalent),70517,1352344,2004572,69295.13,70675.27,71786.18,77413.80,78055.95
Sugar Crops,66146,1445276,2127345,322467.52,317423.30,314772.13,315572.36,326132.77
Sugar beet,33784,616491,1108508,40090.00,47240.00,47244.00,45332.00,44685.00
Sugar cane,59554,1133592,1913174,282380.51,270179.30,267526.12,270238.36,281447.76
Sugar non-centrifugal,18769,307461,526787,236.98,230.85,185.80,204.68,215.68
Sunflower seed,57326,999787,1677799,11136.14,10686.98,6749.09,7545.63,7500.39
Sunflowerseed Oil,70253,1348252,1957077,6126.70,4986.00,4901.51,6432.42,5996.97
Sweet potatoes,74062,1393150,2131142,68785.44,67762.36,69849.89,76488.54,77209.90
"Sweeteners, Other",77144,1464768,2244222,8034.54,8593.45,8277.40,8667.08,8701.86
Tea (including mate),65694,1280610,1759540,2716.24,2627.37,2652.44,2599.72,2834.23
Tomatoes and products,74112,1440954,2117921,68147.92,68981.37,62570.48,61712.96,63750.78
Treenuts,70304,1525888,1962812,6523.47,6939.31,6319.69,6875.08,6886.56
Vegetable Oils,76734,1675550,2228663,59740.35,60659.38,58312.01,67913.02,68401.90
Vegetables,78335,1712866,2295933,256648.34,264068.13,256219.45,259140.62,268337.49
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

### What is the total Protein supply quantity in Madagascar in 2015?

In [16]:
df[df.Area == "Madagascar"].groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,15351,318888,630819,31578.76,31214.98,31732.08,31927.87,32596.87
Export Quantity,13416,279445,614744,425.48,494.75,535.06,566.81,535.81
Fat supply quantity (g/capita/day),14319,299405,75924,88.72,91.85,95.33,101.03,96.43
Feed,4515,94030,193235,2178.76,2070.22,2121.40,2059.60,2133.60
Food,14190,295817,565620,21405.42,21120.65,21435.61,21676.21,22116.21
Food supply (kcal/capita/day),14319,299405,73704,7945.00,7685.00,7669.00,7768.00,7748.00
Food supply quantity (kg/capita/yr),14190,295817,70950,907.59,871.59,861.17,847.75,842.17
Import Quantity,14319,297945,622821,2010.71,1721.80,1901.47,3139.79,3214.79
Losses,7095,148102,281765,2252.00,2176.00,2215.00,2153.00,2253.00
Other uses (non-food),6579,138246,262854,4348.58,3957.12,4114.08,4170.06,4221.06
Processing,9804,201929,389956,1262.00,1803.00,1770.00,1826.00,1819.00
Production,14190,295071,606210,30337.51,29482.89,29889.65,29267.86,30215.86
Protein supply quantity (g/capita/day),14319,299405,74814,177.79,173.05,173.40,175.75,176.64
Residuals,13545,280011,542850,-603.00,-616.00,-642.00,-657.00,-676.00
Seed,2709,56067,116067,728.00,699.00,720.00,695.00,728.00
Stock Variation,12642,262174,497056,352.00,-505.00,-475.00,-91.00,293.00
Total Population - Both sexes,129,2501,511,23590.00,24234.00,24894.00,25571.00,26262.00

### What is the total number of unique countries in the dataset?

In [61]:
df.Area.nunique()

49

### Which year had the least correlation with ‘Element Code’?

In [63]:
df.corr()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

### What is the total number and percentage of missing data in 2014 to 3 decimal places?

In [64]:
df.Y2014.isna().sum()/df.shape[0]

0.026073544131401474

### Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the highest sum in 2017?

In [65]:
df[['Y2017', 'Area']].groupby('Area').sum().sort_values(by = 'Y2017', ascending = False)

                                  Y2017
Area
Nigeria                      1483268.23
Egypt                         866379.92
South Africa                  517590.54
Ethiopia                      448683.76
Morocco                       388495.36
Ghana                         337599.06
Algeria                       325644.27
United Republic of Tanzania   322616.85
Kenya                         264660.66
Sudan                         239931.92
Cameroon                      232030.43
Angola                        229159.57
Côte d'Ivoire                 224599.01
Uganda                        213950.38
Malawi                        181098.71
Mozambique                    161407.98
Mauritania                    156665.46
Mali                          149928.33
Madagascar                    131197.73
Niger                         126707.58
Benin                         124771.22
Tunisia                       124167.20
Zambia                        103223.77
Burkina Faso                  101855.07
Guinea                         98138.87
Senegal                        95681.15
Zimbabwe                       75919.34
Rwanda                         73663.69
Chad                           71594.68
Sierra Leone                   55311.33
Eswatini                       54343.33
Mauritius                      51114.83
Togo                           49841.88
Congo                          41181.68
Central African Republic       29937.00
Namibia                        29874.89
Liberia                        29342.20
Gabon                          27979.64
Gambia                         23154.18
Djibouti                       22729.91
Botswana                       22101.30
Lesotho                        21267.96
Guinea-Bissau                  19102.77
Cabo Verde                     14650.74
Sao Tome and Principe          12662.63
Seychelles                       442.34
Comoros                           59.84
Sudan (former)                     0.00
Ethiopia PDR                       0.00

### Perform a groupby operation on ‘Element’.  What year has the highest sum of Stock Variation?
&
### Perform a groupby operation on ‘Element’.  What is the total number of the sum of Processing in 2017?

In [53]:
df.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

### Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the 7th lowest sum in 2017?

In [66]:
df[['Y2017', 'Area']].groupby('Area').sum().sort_values(by = 'Y2017')

                                  Y2017
Area
Sudan (former)                     0.00
Ethiopia PDR                       0.00
Comoros                           59.84
Seychelles                       442.34
Sao Tome and Principe          12662.63
Cabo Verde                     14650.74
Guinea-Bissau                  19102.77
Lesotho                        21267.96
Botswana                       22101.30
Djibouti                       22729.91
Gambia                         23154.18
Gabon                          27979.64
Liberia                        29342.20
Namibia                        29874.89
Central African Republic       29937.00
Congo                          41181.68
Togo                           49841.88
Mauritius                      51114.83
Eswatini                       54343.33
Sierra Leone                   55311.33
Chad                           71594.68
Rwanda                         73663.69
Zimbabwe                       75919.34
Senegal                        95681.15
Guinea                         98138.87
Burkina Faso                  101855.07
Zambia                        103223.77
Tunisia                       124167.20
Benin                         124771.22
Niger                         126707.58
Madagascar                    131197.73
Mali                          149928.33
Mauritania                    156665.46
Mozambique                    161407.98
Malawi                        181098.71
Uganda                        213950.38
Côte d'Ivoire                 224599.01
Angola                        229159.57
Cameroon                      232030.43
Sudan                         239931.92
Kenya                         264660.66
United Republic of Tanzania   322616.85
Algeria                       325644.27
Ghana                         337599.06
Morocco                       388495.36
Ethiopia                      448683.76
South Africa                  517590.54
Egypt                         866379.92
Nigeria                      1483268.23